export const RatingTypes = {
    START_LOAD_LIST:'START_LOAD_LIST',
    SUCCESS_LOAD_LIST:'SUCCESS_LOAD_LIST',
    FAILURE_LOAD_LIST:'FAILURE_LOAD_LIST',
    SET_RATING_FILTER:'SET_RATING_FILTER',
    SHOW_ME_IN_LIST:'SHOW_ME_IN_LIST',
    CHANGE_PAGE: 'CHANGE_PAGE',
}