
export const ActivityFormActionTypes = {
    OPEN_ACTIVITIES_FORM:'OPEN_ACTIVITIES_FORM',
    CLOSE_ACTIVITIES_FORM:'CLOSE_ACTIVITIES_FORM',
    START_REQUEST_ACTIVITY_FORM:'START_REQUEST_ACTIVITY_FORM',
    SUCCESS_REQUEST_ACTIVITY_FORM:'SUCCESS_REQUEST_ACTIVITY_FORM',
    FAILURE_REQUEST_ACTIVITY_FORM:'FAILURE_REQUEST_ACTIVITY_FORM',
}