export const AuthActionTypes = {
    USER_AUTH_REQUEST_START:'USER_AUTH_REQUEST_START',
    USER_AUTH_REQUEST_SUCCESS:'USER_AUTH_REQUEST_SUCCESS',
    USER_AUTH_REQUEST_FAILURE:'USER_AUTH_REQUEST_FAILURE',
    USER_AUTH_LOGOUT:'USER_AUTH_LOGOUT',
    USER_AUTH_FAILURE_RESET:'USER_AUTH_FAILURE_RESET',
    SET_CURRENT_USER:'SET_CURRENT_USER',
    GET_TOTAL_POINTS: 'GET_TOTAL_POINTS', 
    GET_TOTAL_POINTS_FAILURE: 'GET_TOTAL_POINTS_FAILURE',
}