
export const ActivitiesActionTypes = {
    START_LOAD_ACTIVITIES:'START_LOAD_ACTIVITIES',
    SUCCESS_LOAD_ACTIVITIES:'SUCCESS_LOAD_ACTIVITIES',
    FAILURE_LOAD_ACTIVITIES:'FAILURE_LOAD_ACTIVITIES',
}