export const EditProfileTypes = {
    START_EDIT_USER_REQUEST:'START_EDIT_USER_REQUEST',
    SUCCESS_EDIT_USER_REQUEST:'SUCCESS_EDIT_USER_REQUEST',
    FAILURE_EDIT_USER_REQUEST:'FAILURE_EDIT_USER_REQUEST'
}
