export const EditProfileTypes = {
    START_EDIT_USER_REQUEST:'START_EDIT_USER_REQUEST',
    SUCCESS_EDIT_USER_REQUEST:'SUCCESS_EDIT_USER_REQUEST',
    FAILURE_EDIT_USER_REQUEST:'FAILURE_EDIT_USER_REQUEST',
    START_TASKS_DONE_REQUEST:'START_TASKS_DONE_REQUEST',
    SUCCESS_TASKS_DONE_REQUEST:'SUCCESS_TASKS_DONE_REQUEST',
    FAILURE_TASKS_DONE_REQUEST:'FAILURE_TASKS_DONE_REQUEST',
}
