export const TaskHistoryTypes = {
    START_LOAD_TASKS_REQUEST:'START_LOAD_TASKS_REQUEST',
    SUCCESS_LOAD_TASKS_REQUEST:'SUCCESS_LOAD_TASKS_REQUEST',
    FAILURE_LOAD_TASKS_REQUEST:'FAILURE_LOAD_TASKS_REQUEST',
    CHANGE_PAGE: 'CHANGE_PAGE',
}
